# Definición completa del espacio de búsqueda de hiperparámetros

dqn_hyperparameters:
  learning_rate: 
    min: 0.0001
    max: 0.005
    type: float
    description: "Adam optimizer learning rate - conservador para estabilidad"
    
  gamma: 
    min: 0.95
    max: 0.999
    type: float
    description: "Discount factor - alto para horizontes largos en carga EV"
    
  epsilon_start: 
    min: 0.8
    max: 1.0
    type: float
    description: "Initial exploration rate - exploración fuerte"
    
  epsilon_min: 
    min: 0.01
    max: 0.05
    type: float
    description: "Minimum exploration rate - convergencia estable"
    
  epsilon_decay: 
    min: 0.995
    max: 0.999
    type: float
    description: "Exploration decay rate - decay lento para mejor exploración"
    
  batch_size: 
    values: [32, 64, 128, 256]
    type: int_discrete
    description: "Training batch size - eliminado 16 por ser muy pequeño"
    
  target_update_freq: 
    values: [10, 20, 30, 50, 100]
    type: int_discrete
    description: "Target network update frequency"
    
  memory_size: 
    values: [10000, 20000, 50000]
    type: int_discrete
    description: "Experience replay buffer size - aumentados para mejor replay"
    
  dueling_network: 
    values: [True, False]
    type: bool
    description: "Use Dueling DQN architecture vs standard DQN"

reward_weights:
  energy_satisfaction_weight: 
    min: 0.3
    max: 3.0
    type: float
    current_baseline: 1.0
    description: "Weight for energy satisfaction in reward function"
    
  energy_cost_weight: 
    min: 0.01
    max: 1.0
    type: float
    current_baseline: 0.1
    description: "Weight for energy cost in reward function"
    
  penalty_skipped_vehicle: 
    min: 10.0
    max: 200.0
    type: float
    current_baseline: 50.0
    description: "Penalty for vehicles not assigned to charging"
    
  reward_assigned_vehicle: 
    min: 1.0
    max: 100.0
    type: float
    current_baseline: 20.0
    description: "Reward for successfully assigning vehicles"

# Definiciones de arquetipos para diversidad garantizada
archetypes:
  cost_minimizer:
    energy_cost_weight: [0.6, 1.0]
    energy_satisfaction_weight: [0.3, 0.8]
    description: "Prioritizes cost reduction over satisfaction"
    
  satisfaction_maximizer:
    energy_satisfaction_weight: [2.0, 3.0]
    energy_cost_weight: [0.01, 0.2]
    description: "Prioritizes complete energy satisfaction"
    
  balanced_optimizer:
    energy_satisfaction_weight: [1.0, 1.8]
    energy_cost_weight: [0.2, 0.6]
    description: "Balanced approach to cost and satisfaction"
    
  urgency_focused:
    penalty_skipped_vehicle: [120, 200]
    reward_assigned_vehicle: [60, 100]
    description: "Never leaves vehicles unattended"
    
  efficiency_focused:
    reward_assigned_vehicle: [70, 100]
    penalty_skipped_vehicle: [10, 40]
    description: "Maximizes throughput and assignments"

# Validación y restricciones adicionales
validation:
  # Restricción: energy_satisfaction_weight + energy_cost_weight debe ser balanceado
  balance_constraints:
    max_total_weight: 4.0  # suma máxima de satisfaction + cost weights
    min_total_weight: 0.5  # suma mínima
    
  # Restricción: penalty vs reward debe ser proporcional
  penalty_reward_ratio:
    max_ratio: 20.0  # penalty no debe ser más de 20x el reward
    min_ratio: 0.1   # penalty no debe ser menos de 0.1x el reward