# Scatter Search algorithm configuration for hyperparameter optimization

algorithm:
  # Population parameters
  population_size: 200
  ref_set_size: 20
  elite_count: 12
  diverse_count: 8
  max_iterations: 50
  max_time_hours: 60
  
  # Operation probabilities
  combination_probability: 0.9
  improvement_probability: 0.6
  
  # Convergence criteria
  min_improvement_threshold: 0.005
  patience_iterations: 8

evaluation:
  # FAST EVALUATION - Initial aggressive filtering
  fast:
    systems: [1,2,3]  # System IDs for fast evaluation
    episodes: 30
    description: "Initial Filtering - RTX 4090"
    
  # MEDIUM EVALUATION - Promising candidates
  medium:
    systems: [1, 2, 3, 4, 5,6,7,8,9]
    episodes: 60
    description: "Medium evaluation for promising candidates"
    
  # Full evaluation: all available systems
  full:
    systems: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
    episodes: 80
    description: "Complete evaluation for best candidates"

output:
  # Output and checkpoint configuration
  save_frequency: 3  # Save every N iterations
  checkpoint_dir: "./checkpoints/scatter_search"
  
  # Report configuration
  generate_plots: true
  generate_excel: true
  create_deployment_package: true
  
  # Logging configuration
  log_level: "INFO"
  detailed_logging: true

diversity:
  # Diversity control parameters
  similarity_threshold_initial: 0.98
  similarity_threshold_final: 0.75
  adaptive_threshold: true
  
  # Similarity metric
  similarity_metric: "cosine"  # options: "cosine", "euclidean"
  
quality:
  # Quality assurance parameters
  min_evaluations_per_config: 1
  fitness_aggregation: "mean"  # options: "mean", "median", "min"
  
  # Filtering criteria
  filter_invalid_configs: true
  min_fitness_threshold: -4000.0

resources:
  # Computational resources configuration
  parallel_evaluation: false  # For future development
  max_concurrent_jobs: 1
  
  # Memory limits
  max_memory_gb: 20
  cleanup_frequency: 3  # Clean memory every N iterations

debug:
  # Debug configuration
  verbose_output: true
  save_intermediate_results: true
  track_convergence: true
  
  # Testing configuration
  test_mode: false
  quick_test: false  # Use only 1 system and 5 episodes