# Configuraci칩n completa del algoritmo Scatter Search
algorithm:
  population_size: 150
  ref_set_size: 10
  max_iterations: 8
  max_time_hours: 48
  
  elite_count: 6
  diverse_count: 4
  
  combination_probability: 0.7
  improvement_probability: 0.5
  
  # Par치metros de combinaci칩n
  alpha_range: [0.2, 0.8]
  extrapolation_probability: 0.1
  
  # Par치metros de mejora local
  perturbation_strength: 0.05
  max_improvement_iterations: 3

evaluation:
  fast:
    episodes: 30
    systems: [1, 5]
    time_budget_hours: 12
    
  medium:
    episodes: 100
    systems: [1, 3, 5, 7]
    time_budget_hours: 24
    
  full:
    episodes: 200
    systems: "all"
    time_budget_hours: 12

computation:
  max_workers: 8
  batch_parallel: true
  gpu_allocation: "auto"
  memory_limit_gb: 16

diversity:
  min_distance_threshold: 0.15
  archetype_representation: true
  force_archetype_minimum: 2
  distance_metric: "euclidean_normalized"

output:
  save_frequency: 2
  checkpoint_dir: "./scatter_search_checkpoints"
  results_dir: "./scatter_search_results"
  detailed_logging: true
  generate_visualizations: true